spring:
  cloud:
    gateway:
      routes:
#路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: cloud-service-payment1
#匹配后提供服务的路由地址
          uri: http://localhost:8001
#断言,路径相匹配的进行路由
          predicates:
            - Path= /payment/**
        - id: cloud-service-payment2
          uri: http://localhost:8002
          predicates:
            - Path= /payment8002/**

#Eureka
#eureka:
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      default-zone: http://eureka7001.com:7001/eureka
